title: ManingSport
description: >- # this means to ignore newlines until "baseurl:"
  O Desporto Rei ao seu Alcance
url: "https://maning.sport"

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-email-protect 
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-analytics
  - jekyll-feed

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-73721868-1       # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bower_components

sass:
  sass_dir: assets/_sass
  style: compressed

image: /assets/img/logotipo.jpeg

pagination:
  enabled: true
  per_page: 15
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

image:
logo: /assets/img/brand/logotipo.svg
color: "#f56a6a"